version: '3.7'

services:

  db:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_DB_FILE}:/var/lib/mysql
    networks:
      - ${APP_NETWORK:-appnet}

  worker:
    build:
      context: ./worker
    image: worker:local
    container_name: worker
    restart: always
    environment:
      MQTT_SERVICE: ${MQTT_SERVICE}
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_USER: ${MQTT_USER}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
      MQTT_TOPIC: ${MQTT_TOPIC}  
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
      LOG_LEVEL: ${LOG_LEVEL}
    volumes:
      - ${PATH_LOG}:/opt/app/log
    networks:
      - ${APP_NETWORK:-appnet}
    depends_on:
      - db

  web:
    build:
      context: ./web
    image: webapp:local
    container_name: webapp
    restart: always
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
      FLASK_APP: ${FLASK_APP:-app.py}
      FLASK_ENV: ${FLASK_ENV:-production}
      LOG_LEVEL: ${LOG_LEVEL}
      SECRET_KEY: ${FLASK_SECRET_KEY}
      SERVER_NAME: ${SERVER_NAME}
      PREFERRED_URL_SCHEME: ${SERVER_NAME}
    volumes:
      - ${PATH_LOG}:/opt/app/log
    networks:
      - ${APP_NETWORK:-appnet}
    depends_on:
      - db
      - worker

networks:

  appnet:
    #internal: true
    name: ${APP_NETWORK:-appnet}
