version: '3.7'

services:

  klaxdb:
    image: mariadb
    container_name: klaxdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_DB_FILE}:/var/lib/mysql
    networks:
      - klaxdashboard

  worker:
    build:
      context: ./worker
    image: worker:local
    container_name: worker
    restart: always
    environment:
      MQTT_SERVICE: ${MQTT_SERVICE}
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_USER: ${MQTT_USER}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
      MQTT_TOPIC: ${MQTT_TOPIC}  
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
      LOG_LEVEL: ${LOG_LEVEL}
      DEMO_MODE: ${DEMO_MODE}
    volumes:
      - ${PATH_LOG}:/opt/app/log
    networks:
      - klaxdashboard
    depends_on:
      - klaxdb

  klaxapp:
    build:
      context: ./web
    image: klaxapp:local
    container_name: klaxapp
    restart: always
    ports:
      - "8000:8000"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
      LOG_LEVEL: ${LOG_LEVEL}
      DEMO_MODE: ${DEMO_MODE}    
    volumes:
      - ${PATH_LOG}:/opt/app/log
    networks:
      - klaxdashboard
    depends_on:
      - klaxdb
      - worker

networks:

  klaxdashboard:
    #internal: false
    name: klaxdashboard
