version: '3.7'

services:

  db:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_DB_FILE}:/var/lib/mysql
      - ${MYSQL_DB_CNF}:/etc/mysql/conf.d
    networks:
      - ${APP_NETWORK:-appnet}

  worker:
    build:
      context: ./worker
    image: smartenvworker:local
    container_name: smartenvworker
    restart: always
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DB_NAME: smartenv
      LOG_LEVEL: ${LOG_LEVEL}
    volumes:
      - ${PATH_LOG}:/opt/app/log
    networks:
      - ${APP_NETWORK:-appnet}
    depends_on:
      - db

  web:
    build:
      context: ./web
    image: smartenvweb:local
    container_name: smartenvweb
    restart: always
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DB_NAME: smartenv
      FLASK_APP: ${FLASK_APP:-app.py}
      FLASK_ENV: ${FLASK_ENV:-production}
      LOG_LEVEL: ${LOG_LEVEL}
      SECRET_KEY: ${FLASK_SECRET_KEY}
      SERVER_NAME: ${SERVER_NAME}
      PREFERRED_URL_SCHEME: ${SERVER_NAME}
    volumes:
      - ${PATH_LOG}:/opt/app/log
    networks:
      - ${APP_NETWORK:-smartenv}
    depends_on:
      - db
      - worker

networks:

  appnet:
    #internal: true
    name: ${APP_NETWORK:-appnet}
